### PR TITLE
Expose resource names

### LINKED ISSUE #73: Resource trait to expose resource name
Currently, we have to infer the `resource` name from `kind` by pluralising it when creating our `Api` (https://github.com/clux/kube-rs/issues/284)

Is the plural name available when you are generating? I see you are using [pluralised names](https://arnavion.github.io/k8s-openapi/v0.9.x/src/k8s_openapi/v1_18/api/apps/v1/deployment.rs.html#42) somehow, but haven't figured out where it's from.

if it's available, is it possible to add it to the `Resource` trait as another associated const? It would help us drop hacky `inflector` dependencies and avoid potential errors.

### PR DESCRIPTION
**Pull request by MikailBag**
Closes #73

TODO:
 - [x] rollback temporary changes
 - [ ] resolve "TODOs" connected with empty resource name

### CODE REVIEW

**Comment by Arnavion** [comment]
Please call it `PLURAL` or `PLURAL_NAME` rather than `NAME`.

**Comment by MikailBag** [comment]
I have renamed it to be a PLURAL_NAME

**Comment by MikailBag** [comment]
Last two commits additionally expose resource scope (namespace-scoped or cluster-scoped)

**Comment by MikailBag** [comment]
The most technically challenging part here (except parsing URLs :smile: ) is to provide enough information for type-safe cluster-scoped and namespaces resources distinction (e.g. kube-rs would like to statically prevent `Api<Node>::namespaced`).

In this PR, I propose roughly the 
following:
```rust
trait Scope {}
impl Scope for String {}
impl Scope for () {}

trait Resource {
    // ...
   type Scope: Scope;
}

// generated: 
// cluster-scoped example
impl Resource for Node {
   // ...
   type Scope = ();
}
// namespace example
impl Resource for Pod {
    // ...
   type Scope = String;
}
```

These type-level markers can then be used as type bounds in generic implementations.

However, the current state is not ideal, because the following code is rejected by the compiler:

```rust
struct Api<R>(std::marker::PhantomData<R>);

impl<R: Resource<Scope=String>> Api<R> {
    fn new(ns: &str) -> Self {
        todo!()
    }
}

impl<R: Resource<Scope=()>> Api<R> {
    fn new() -> Self {
        todo!()
    }
}
```
with an error `duplicate definitions with name "new"`. It seems like a compiler limitation, and I can't think of a workaround.
However, I think that even in the current state this PR exposes enough additional information to make generic API clients more correct and safe.

cc @clux

**Comment by Arnavion** [comment]
Yes, I went over this in https://github.com/Arnavion/k8s-openapi/issues/65#issuecomment-601839119

**Comment by Arnavion** [comment]
Just checking, this isn't ready for review yet, yes? I say this based on the unchecked TODO in the OP.

**Comment by MikailBag** [comment]
I think it can be reviewed.

I'd like to hear your opinion regarding those empty strings (e.g. this PR assigns empty resource name for every List, which is not really invalid, but can be confusing)

**Comment by Arnavion** [comment]
Is there a reason to use `String` and `()` ? If not, it should create new `ClusterScopedResource` and `NamespaceScopedResource` types and use those, like what I wrote in the second bullet-point in https://github.com/Arnavion/k8s-openapi/issues/65#issuecomment-601839119

>- instead adding `const SCOPE: ResourceScope` to `Resource` with `trait ResourceScope { } struct ClusterScopedResource; impl ResourceScope for ClusterScopedResource { } struct NamespaceScopedResource; impl ResourceScope for NamespaceScopedResource { } struct NotScopedResource; impl ResourceScope for NotScopedResource { }`

Though since `const`s can't be used for trait bounds, it should be `type Scope: ResourceScope;` like your current implementation.

**Comment by Arnavion** [comment]
As for List's `PLURAL_NAME` it depends on what `PLURAL_NAME` would be used for (by you or anyone else)? If it's just for constructing CRUD URLs dynamically, it should be fine because such URLs don't exist for lists.

**Pull request closed without merging**
