### PR TITLE
Remove support for k8s v1.18

### PR DESCRIPTION
**Pull request by jesperpedersen**
Signed-off-by: jesperpedersen <jesper.pedersen@redhat.com>

### CODE REVIEW

**Comment by jesperpedersen** [comment]
Note, that this pull request enables k8s 1.25 in CI.

I can separate this out if necessary.

**Comment by Arnavion** [comment]
>Remove support for k8s v1.18

I looked at this when I did the kind v0.15.0 update yesterday, and for some reason ACK [still lists 1.18 as a supported version,](https://www.alibabacloud.com/help/en/container-service-for-kubernetes/latest/release-notes-release-notes) so I'd rather not remove it right now.

>Note, that this pull request enables k8s 1.25 in CI.

Ah yes, whoops.

**Comment by jesperpedersen** [comment]
Commercial vendors may support k8s version longer internally, but customers on those platform would stick on existing software - e.g. not develop new stuff.

But, feel free to close.

**Comment by Arnavion** [comment]
Yeah just checked again before I do a release, and it's still there, so I'd rather not remove it for now.

Since Rust and the crates.io ecosystem (including k8s-openapi) generally doesn't have a policy of supporting older version lines, it's probably not uncommon for users to update their Rust deps even though everything else about their setup is old enterprise LTS. For example $dayjob updates Rust and deps even in its multi-year LTS branches, for this reason.

I've taken just the missing CI part of this change.

**Comment by jesperpedersen** [comment]
No worries - kind 0.15 still has a 1.18 image... although I don't know why

**Pull request closed without merging**
